### ISSUE TITLE
Download files not updated since 2022-07-19

### ISSUE THREAD

**Issue by AngieHinrichs** [COG-UK/dipi-group#210]
@WhalleyT the download files haven't been updated in a couple days, can you take a look?
```
curl -s -I https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta.gz | grep Last-Modified
Last-Modified: Tue, 19 Jul 2022 02:04:13 GMT
```
Thanks!

**Comment by nickloman** [comment]
Hi @AngieHinrichs - thanks for the report. There were some transient issues with `datapipe` which produces these files caused by unavailable server resource due to a partial data centre shutdown following the unseasonably high temperatures here on Monday and Tuesday (>40C!). The pipeline looks to be running normally again now.

**Comment by AngieHinrichs** [comment]
Thanks!  Ugh, I should have guessed that the heat wave threatened to cook the servers.  Glad it has passed.
